### ISSUE TITLE
Adapt for Braille display: turn 90 degrees and shrink

### ISSUE THREAD

**Issue by pachpict** [blueOkiris/tetris-cli#1]
I am interested in adapting your Tetris program to fit onto the Canute 360 9-line Braille display, a not-for-profit device built for blind Braille users (https://bristolbraille.org/).

For this to work with your program:

 - The characters would have to move from the right to the left of the display (in other words rotate 90 degrees clockwise).
 - They would have to be single character per block, e.g. `====` rather than `[00][00][00][00]`. (I use equals signs because they transcribe, using Braille ASCII on a Braille display, to `⠿`.)
 - It would have to move at about 1/5th the speed.
 - Would need the 'width' (what is currently the horizontal but on this version would be the vertical) reduced to 9 lines, removing the `[<>]` walls.

I have had a quick play around but this is beyond my immediate knowledge. So I thought I would raise an issue in case it interested you to see your game be the first one ported to a multiline Braille display, as you might be able to make the changes listed above very quickly. If so, great, I'll test it and propose a patch or write up my test findings. If not, no problem.

Either way feel free to contact me using the details on the website above. Regards, Ed Rogers, Bristol Braille Technology CIC

**Comment by blueOkiris** [comment]
FYI. I rewrote this project to be written in Rust, use modern code practices, have colors, and use a better display library, so the C code is no longer available in the master branch

This means if you intend to make the braille version you'll need the old C code, so I'm making a note that the commit you want to base it off of is [fbaeb321fe8b6e263fb6232a293e4131ee1ca306](https://github.com/blueOkiris/tetris-cli/commit/fbaeb321fe8b6e263fb6232a293e4131ee1ca306).
