### ISSUE TITLE
Not Linux-only

### ISSUE THREAD

**Issue by 0323pin** [blueOkiris/tetris-cli#3]
Hi,

Any reason to label this project **Linux only**?
I've just packaged this for NetBSD and as you can see from the screenshot, it's working as it should.

![2022-06-07-114430_1366x768_scrot](https://user-images.githubusercontent.com/90570748/172350867-a8e921f6-00ce-453e-a260-a3ee38584203.png)

Suggestion to change Linux to ***nix**.

I've ~~will~~ [merged this into our repositories](https://mail-index.netbsd.org/pkgsrc-changes/2022/06/07/msg255638.html) ~~soon~~ and users will be able to install it by simply running `pkgin install tetris-cli`
I wonder if you want to make my life easier as package maintainer and remove `Cargo.lock` from `.gitignore`. We have a script that reads `Cargo.lock` to automatically list all the dependency crates. If `Cargo.lock` isn't present in the repository, I have to this manually.

Thanks!

**Comment by blueOkiris** [comment]
Tbh I said Linux-only only bc I didn't even think of BSD lol. But yeah, I mostly just meant it wouldn't work in Windows terminal and couldn't test Mac to know, so I'll update the readme.

And sure, I can add the Cargo.lock to the repo for this use case

**Comment by blueOkiris** [comment]
Should be good now

**Comment by 0323pin** [comment]
@blueOkiris Yes, thanks! I might do a PR to add install instructions to the README.md at a later stage. Don't have my machine with me right now.
